---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "csv",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "graphql",
      "helm",
      "html",
      "jq",
      "javascript",
      "json",
      "json5",
      "jsonc",
      "lua",
      "make",
      "markdown",
      "mermaid",
      "proto",
      "python",
      "ruby",
      "rust",
      "scss",
      "sql",
      "ssh_config",
      "terraform",
      "tmux",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vue",
      "yaml",
    },
  },
}
